### PR TITLE
[1.1.3-3]: FP-2811 - With operator role, when using a layout I can wrongfully select wrong menus

### PR DESCRIPTION
**Pull request by quirinpa**
- [FP-2811](https://movai.atlassian.net/browse/FP-2811): With operator role, when using a layout I can wrongfully select wrong menus

[FP-2811]: https://movai.atlassian.net/browse/FP-2811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by diasdm — CHANGES_REQUESTED** [review]
The app the bugfix is pertaining to depends on lib-react `1.1.2-6`, the last build on this version is `1.1.2-29`, but you branched out from `1.1.2-17`. Is there a clear plan?

**Comment by quirinpa** [comment]
Yes. I could not 1.1.2-29 to work because the theming solution was not working properly with the current stack. 17 was more viable for this reason.

**Comment by manuelnogueiramov** [comment]
> Yes. I could not 1.1.2-29 to work because the theming solution was not working properly with the current stack. 17 was more viable for this reason.

`1.1.2-17` contains tty/styles whilst `1.1.2-29` doesn't. I understand why @diasdm asked his question. Please try to fix this issue using `1.1.2-29`. Thank you.

**Comment by manuelnogueiramov** [comment]
> Yes. I could not 1.1.2-29 to work because the theming solution was not working properly with the current stack. 17 was more viable for this reason.

`1.1.2-17` contains tty/styles whilst `1.1.2-29` doesn't. I understand why @diasdm asked his question. Please try to fix this issue using `1.1.2-29`. Thank you.

**Comment by quirinpa** [comment]
That is why in the original PR I removed @tty-pt/styles

**Comment by quirinpa** [comment]
That is why in the original PR I removed @tty-pt/styles. But Tiago said that I shouldn't remove it. So I created this new one.
Check the history please.

29 could not be used effectively.

**Pull request closed without merging**
