### PR TITLE
FP-2033 : Remove unused libraries

### PR DESCRIPTION
**Pull request by RianMartins-Movai**
FP-2033 : Update dependencies
- Uninstall unused libraries
  - @babel/runtime
  - date-fns
- Move from devDependencies to dependencies
  - @material-ui/core
  - @material-ui/icons
  - @material-ui/lab
  - @material-ui/styles

### CODE REVIEW

**Review by jebesampaio — CHANGES_REQUESTED** [review]
Here is the same as in lib-core. @types/node is still installed because some packages require it. If not declaring explicitly declaring it, we are depending other libraries to have access to these node types, console.log for example: 

image

**Comment by RianMartins-Movai** [comment]
> Here is the same as in lib-core. @types/node is still installed because some packages require it. If not declaring explicitly declaring it, we are depending other libraries to have access to these node types, console.log for example:
> 

In that case, I didn't uninstall the @types/node. I just moved some dev dependencies to their right place and uninstalled other used libs. 
I'll fix this in lib-core, but I believe this PR is good to go.

Please let me know what you think.

**Comment by jebesampaio** [comment]
> > Here is the same as in lib-core. @types/node is still installed because some packages require it. If not declaring explicitly declaring it, we are depending other libraries to have access to these node types, console.log for example:
> 
> Hi, @jebesampaio In that case, I didn't uninstall the @types/node. I just moved some dev dependencies to their right place and uninstalled other used libs. I'll fix this in lib-core, but I believe this PR is good to go.
> 
> Please let me know what you think.

Maybe I was looking at the lib-core PR instead of this one, sorry :sweat_smile:  Good to go :muscle:

**Review by jebesampaio — APPROVED** [review]
Maybe I was looking at the lib-core PR instead of this one, sorry :sweat_smile:  Good to go :muscle:

**Pull request merged**
